// <auto-generated />
using System;
using GuestBook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GuestBook.Migrations
{
    [DbContext(typeof(GuestBookContext))]
    partial class GuestBookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GuestBook.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("736e92cf-2d33-4e7e-91f3-edb01b284a31"),
                            Content = "I was here1",
                            CreateTime = new DateTime(2022, 7, 13, 9, 4, 23, 171, DateTimeKind.Local).AddTicks(8876),
                            Email = "mariusz@gmail.com",
                            Name = "Mariusz"
                        },
                        new
                        {
                            Id = new Guid("440bcfb7-0f60-4a9b-9b50-9b5f405cd7dc"),
                            Content = "I was here2",
                            CreateTime = new DateTime(2022, 7, 13, 9, 4, 23, 177, DateTimeKind.Local).AddTicks(9034),
                            Email = "mariusz@gmail.com",
                            Name = "Marian"
                        },
                        new
                        {
                            Id = new Guid("0513af24-4872-4bfa-80c9-328d43346ecd"),
                            Content = "I was here3",
                            CreateTime = new DateTime(2022, 7, 13, 9, 4, 23, 177, DateTimeKind.Local).AddTicks(9113),
                            Email = "mariusz@gmail.com",
                            Name = "Maria"
                        },
                        new
                        {
                            Id = new Guid("28185d09-eb75-475b-a527-5a4b1fe64a64"),
                            Content = "I was here4",
                            CreateTime = new DateTime(2022, 7, 13, 9, 4, 23, 177, DateTimeKind.Local).AddTicks(9122),
                            Email = "mariusz@gmail.com",
                            Name = "Mateusz"
                        },
                        new
                        {
                            Id = new Guid("e4c01e26-799f-4677-87cb-11dadb7302ff"),
                            Content = "I was here5",
                            CreateTime = new DateTime(2022, 7, 13, 9, 4, 23, 177, DateTimeKind.Local).AddTicks(9127),
                            Email = "mariusz@gmail.com",
                            Name = "Michal"
                        },
                        new
                        {
                            Id = new Guid("93230c51-44db-439f-ab49-3f4060ea967b"),
                            Content = "I was here6",
                            CreateTime = new DateTime(2022, 7, 13, 9, 4, 23, 177, DateTimeKind.Local).AddTicks(9135),
                            Email = "mariusz@gmail.com",
                            Name = "Milosz"
                        },
                        new
                        {
                            Id = new Guid("dab67b21-0cb4-4941-914f-787739a7bc9e"),
                            Content = "I was here7",
                            CreateTime = new DateTime(2022, 7, 13, 9, 4, 23, 177, DateTimeKind.Local).AddTicks(9141),
                            Email = "mariusz@gmail.com",
                            Name = "Marzena"
                        },
                        new
                        {
                            Id = new Guid("dcff7868-a4a7-4040-8af7-da9ae1c9cc86"),
                            Content = "I was here8",
                            CreateTime = new DateTime(2022, 7, 13, 9, 4, 23, 177, DateTimeKind.Local).AddTicks(9146),
                            Email = "mariusz@gmail.com",
                            Name = "Milena"
                        },
                        new
                        {
                            Id = new Guid("36f3f8d0-18cd-43b7-8c20-dd9c540889cd"),
                            Content = "I was here9",
                            CreateTime = new DateTime(2022, 7, 13, 9, 4, 23, 177, DateTimeKind.Local).AddTicks(9163),
                            Email = "mariusz@gmail.com",
                            Name = "Marlena"
                        },
                        new
                        {
                            Id = new Guid("66819e43-f281-4ec7-87ea-86ed5cab77b7"),
                            Content = "I was here10",
                            CreateTime = new DateTime(2022, 7, 13, 9, 4, 23, 177, DateTimeKind.Local).AddTicks(9171),
                            Email = "mariusz@gmail.com",
                            Name = "Marek"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
